# ================================
# APPLICATION CONFIGURATION
# ================================
spring.application.name=Healthcare-System


# ================================
# DATABASE CONFIGURATION (TiDB)
# ================================
spring.datasource.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/test?sslMode=VERIFY_IDENTITY
spring.datasource.username=4De9nTDyXb6T4P4.root
spring.datasource.password=sfwd3sJO0whp5XSQ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ================================
# JPA CONFIGURATION
# ================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# ================================
# GMAIL SMTP CONFIGURATION
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=srujandeshmukh9@gmail.com
spring.mail.password=rjozgzeetcklusny

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true


# ================================
# SERVER CONFIGURATION
# ================================
server.port=8080


# ================================
# LOGGING CONFIG
# ================================
logging.level.org.springframework.mail=DEBUG
logging.level.org.hibernate.SQL=DEBUG